export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

export const GET_DONATIONS = 'GET_DONATIONS';
export const ADD_COMMENT = 'ADD_COMMENT';
export const ADD_DONATION = 'ADD_DONATION';
export const DONATION_ERROR = 'DONATION_ERROR';

export const DONATION_STAGING = 'DONATION_STAGING';

export const TOGGLE_KOREAN = 'TOGGLE_KOREAN';
export const TOGGLE_ENGLISH = 'TOGGLE_ENGLISH'

